eclipse/microprofile-fault-tolerance

- api/src/main/java/org/eclipse/microprofile/fault/tolerance/cdi/Retry.java
> #2 add retry tidyup

- api/src/main/java/org/eclipse/microprofile/fault/tolerance/cdi/CircuitBreaker.java
> #3 add circuit breaker

- tck/pom.xml
> microprofile-fault-tolerance-19 MP config API coordinates are wrong

- api/src/main/java/org/eclipse/microprofile/fault/tolerance/inject/CircuitBreaker.java
- api/src/main/java/org/eclipse/microprofile/fault/tolerance/inject/Retry.java
- api/src/main/java/org/eclipse/microprofile/fault/tolerance/inject/TimeOut.java
> microprofile-fault-tolerance-18 Add ElementType.TYPE to annotations @Target

- api/src/main/java/org/eclipse/microprofile/fault/tolerance/inject/CircuitBreaker.java
- api/src/main/java/org/eclipse/microprofile/fault/tolerance/inject/Retry.java
- api/src/main/java/org/eclipse/microprofile/fault/tolerance/inject/TimeOut.java
> Fix the missing "Inherited" to some of annotations

- api/src/main/java/org/eclipse/microprofile/fault/tolerance/inject/CircuitBreaker.java
- api/src/main/java/org/eclipse/microprofile/fault/tolerance/inject/Retry.java
> small tweek to tidy up

- api/src/main/java/org/eclipse/microprofile/fault/tolerance/inject/Retry.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/RetryConditionTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/RetryTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClientAbortOn.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClientForMaxRetries.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClientRetryOn.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClientWithDelay.java
> add retry tests

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/RetryConditionTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/RetryTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/CircuitBreakerClient.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClientAbortOn.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClientRetryOn.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClientWithDelay.java
> #tidy up retry tests

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/RetryConditionTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/RetryTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/CircuitBreakerClient.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClientAbortOn.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClientForMaxRetries.java
I've made appropriate changes to the tck retry tests so that they can be run in a server.
> Fix tck retry tests so that they can be run

- api/src/main/java/org/eclipse/microprofile/fault/tolerance/inject/Fallback.java
> #4 Improve the fallback syntax and add some javadoc

- NOTICE
- api/NOTICE
- pom.xml
- tck/NOTICE
- tck/pom.xml
This is in response to Issue #29
> Clean up in prep for IP reviews

- api/src/main/java/org/eclipse/microprofile/fault/tolerance/inject/CircuitBreakerRuntimeException.java
- api/src/main/java/org/eclipse/microprofile/fault/tolerance/inject/FaultToleranceRuntimeException.java
- api/src/main/java/org/eclipse/microprofile/fault/tolerance/inject/TimeoutRuntimeException.java
> #36 add Fault tolerance exception

- api/src/main/java/org/eclipse/microprofile/fault/tolerance/inject/Asynchronous.java
- api/src/main/java/org/eclipse/microprofile/fault/tolerance/inject/FallbackHandler.java
> Improve javadoc on fallback and Asynchronous

- api/src/main/java/org/eclipse/microprofile/faulttolerance/Asynchronous.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/CircuitBreaker.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/ExecutionContext.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/Fallback.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/FallbackHandler.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/Timeout.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/exceptions/CircuitBreakerOpenException.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/exceptions/FaultToleranceException.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/exceptions/TimeoutException.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/package-info.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/CircuitBreakerClient.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClientAbortOn.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClientForMaxRetries.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClientRetryOn.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClientWithDelay.java
> #37 package renaming based on the googlegroup discussion

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/FallbackTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/FallbackA.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/FallbackClient.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/MyBean.java
> #4 add fallback tck

- api/src/main/java/org/eclipse/microprofile/faulttolerance/FallbackHandler.java
> #4 add more javadoc on fallbackhandler

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/FallbackTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/MyBean.java
> #4 improve the test

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/FallbackTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/FallbackA.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/MyBean.java
Fixed a test issue where the test order was throwing off results.
This closes #50
Signed-off-by: John D. Ament <john.d.ament@gmail.com>
> This fixes the bean not being created, missing scope.

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/CircuitBreakerTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/circuitbreaker/clientserver/CircuitBreakerClientDefaultSuccessThreshold.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/circuitbreaker/clientserver/CircuitBreakerClientHigherSuccessThreshold.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/circuitbreaker/clientserver/CircuitBreakerClientNoDelay.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/circuitbreaker/clientserver/CircuitBreakerClientWithDelay.java
> Add Circuit Breaker Tests

- api/src/main/java/org/eclipse/microprofile/faulttolerance/Bulkhead.java
> #27 add bulkhead

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/TimeoutTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/timeout/clientserver/TimeoutClient.java
> Add more Timeout tck tests

- api/src/main/java/org/eclipse/microprofile/faulttolerance/Fallback.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/exceptions/package-info.java
Signed-off-by: Tom Evans <tevans@uk.ibm.com>
> Fix FallbackHandler generics

- api/src/main/java/org/eclipse/microprofile/faulttolerance/exceptions/BulkheadException.java
> #7 Add BulkheadException

- spec/src/main/asciidoc/microprofile-fault-tolerance-spec.asciidoc
- spec/src/main/asciidoc/retry.asciidoc
- spec/src/main/asciidoc/timeout.asciidoc
> #2 add retry spec

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/TimeoutTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/timeout/clientserver/DefaultTimeoutClient.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/timeout/clientserver/ShorterTimeoutClient.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/timeout/clientserver/TimeoutClient.java
> Add class scope timeout tck tests

- spec/src/main/asciidoc/architecture.asciidoc
- spec/src/main/asciidoc/asynchronous.asciidoc
- spec/src/main/asciidoc/execution.asciidoc
- spec/src/main/asciidoc/microprofile-fault-tolerance-spec.asciidoc
- spec/src/main/asciidoc/retry.asciidoc
- spec/src/main/asciidoc/timeout.asciidoc
> tidy up ft spec

- tck/running_the_tck.asciidoc
This closes #53
Signed-off-by: John D. Ament <john.d.ament@gmail.com>
> Adding TCK instructions without needing a tck-suite.xml file.

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/CircuitBreakerTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/circuitbreaker/clientserver/CircuitBreakerClassLevelClientWithDelay.java
> Add class scope CircuitBreaker tck tests

- spec/src/main/asciidoc/bulkhead.asciidoc
> #5 add bulkhead spec

- spec/src/main/asciidoc/architecture.asciidoc
- spec/src/main/asciidoc/circuitbreaker.asciidoc
- spec/src/main/asciidoc/microprofile-fault-tolerance-spec.asciidoc
- spec/src/main/asciidoc/timeout.asciidoc
> tidy up spec structure

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/RetryConditionTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/RetryTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClassLevelClientAbortOn.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClassLevelClientForMaxRetries.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClassLevelClientRetryOn.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClientAbortOn.java
> Add Class scope Retry tck tests

- api/src/main/java/org/eclipse/microprofile/faulttolerance/Asynchronous.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/Bulkhead.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/CircuitBreaker.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/Fallback.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/Timeout.java
> #78 make annotations to be interceptor bindings

- api/src/main/java/org/eclipse/microprofile/faulttolerance/Fallback.java
> #4 address review comments on fallback

- spec/src/main/asciidoc/architecture.asciidoc
- spec/src/main/asciidoc/asynchronous.asciidoc
- spec/src/main/asciidoc/bulkhead.asciidoc
- spec/src/main/asciidoc/microprofile-fault-tolerance-spec.asciidoc
- spec/src/main/asciidoc/relationship.asciidoc
> #tidy up spec and address #76

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/FallbackTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/fallback/clientserver/FallbackClassLevelClient.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/fallback/clientserver/FallbackClient.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/fallback/clientserver/FallbackWithBeanClient.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/fallback/clientserver/MyBean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/fallback/clientserver/SecondStringFallbackHandler.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/fallback/clientserver/StringFallbackHandler.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/fallback/clientserver/StringFallbackHandlerWithBean.java
> Add class scope Fallback test and refactor fallback directory structure

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/CircuitBreakerRetryTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/circuitbreaker/clientserver/CircuitBreakerClassLevelClientWithRetry.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/circuitbreaker/clientserver/CircuitBreakerClientWithRetry.java
> Add CircuitBreaker with Retries test

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/fallback/clientserver/FallbackClassLevelClient.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/fallback/clientserver/FallbackClient.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/fallback/clientserver/FallbackWithBeanClient.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/fallback/clientserver/SecondStringFallbackHandler.java
> #remove commented out imports

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/FallbackTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/fallback/clientserver/FallbackClient.java
> Add fallback with Retries and Timeouts test

- api/src/main/java/org/eclipse/microprofile/faulttolerance/Bulkhead.java
- spec/src/main/asciidoc/bulkhead.asciidoc
- spec/src/main/asciidoc/fallback.asciidoc
> #4 update fallback spec

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/CircuitBreakerRetryTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/FallbackTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/circuitbreaker/clientserver/CircuitBreakerClientWithRetry.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/fallback/clientserver/FallbackClient.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/fallback/clientserver/StringFallbackHandler.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/illegalConfig/FallbackMethodClient.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/illegalConfig/FallbackMethodWithArgsClient.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/illegalConfig/IllegalConfigTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/illegalConfig/IncompatibleFallbackMethodHandler.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/illegalConfig/IncompatibleFallbackMethodTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/illegalConfig/IncompatibleFallbackMethodWithArgsTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/illegalConfig/IncompatibleFallbackTest.java
> Add tests for new Fallback interface

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadAsynchTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadSynchTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/Utils.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BackendTestDelegate.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadClassAsynchronous10Bean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadClassAsynchronous3Bean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadClassAsynchronousDefaultBean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadClassAsynchronousQueueingBean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadClassSemaphore10Bean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadClassSemaphore3Bean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadClassSemaphoreDefaultBean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadMethodAsynchronous10Bean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadMethodAsynchronous3Bean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadMethodAsynchronousDefaultBean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadMethodAsynchronousQueueingBean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadMethodSemaphore10Bean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadMethodSemaphore3Bean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadMethodSemaphoreDefaultBean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadTestBackend.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/Checker.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/ParrallelBulkheadTest.java
Please could you pull this first installment of Bulkhead TCK tests.
> Bulkhead tests 1

- api/src/main/java/org/eclipse/microprofile/faulttolerance/Bulkhead.java
- spec/src/main/asciidoc/bulkhead.asciidoc
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadClassAsynchronousQueueingBean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadMethodAsynchronousQueueingBean.java
> #5 improve bulkhead javadoc and tidy up the annotation

- spec/src/main/asciidoc/configuration.asciidoc
- spec/src/main/asciidoc/microprofile-fault-tolerance-spec.asciidoc
> #43 #58 config FT

- api/src/main/java/org/eclipse/microprofile/faulttolerance/Fallback.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/FallbackHandler.java
Signed-off-by: Tom Evans <tevans@uk.ibm.com>
> Fix-up the generics used in the Fallback annotation

- api/src/main/java/org/eclipse/microprofile/faulttolerance/Bulkhead.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/CircuitBreaker.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/Fallback.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/Timeout.java
> add nonbinding to the interceptor bindings methods

- perform-release/deploy_to_maven_central.sh
- perform-release/prepare_release.sh
> prepare release

- spec/src/main/asciidoc/architecture.asciidoc
> small tidy up to fix the format

- spec/src/main/asciidoc/configuration.asciidoc
> #104 remove namespace

- api/src/main/java/org/eclipse/microprofile/faulttolerance/Fallback.java
> #111 make sure Fallback can only be on method level

- spec/Gemfile
- spec/Guardfile
- spec/README.adoc
- spec/guard.sh
- spec/preview.bat
- spec/preview.sh
- spec/src/main/asciidoc/architecture.asciidoc
- spec/src/main/asciidoc/asynchronous.asciidoc
- spec/src/main/asciidoc/bulkhead.asciidoc
- spec/src/main/asciidoc/circuitbreaker.asciidoc
- spec/src/main/asciidoc/configuration.asciidoc
- spec/src/main/asciidoc/execution.asciidoc
- spec/src/main/asciidoc/fallback.asciidoc
- spec/src/main/asciidoc/microprofile-fault-tolerance-spec.asciidoc
- spec/src/main/asciidoc/relationship.asciidoc
- spec/src/main/asciidoc/retry.asciidoc
- spec/src/main/asciidoc/timeout.asciidoc
Added elements and scripts to ease work on doc
One sentence per line
Typos
Rephrase
> Doc Enhancement

- spec/Gemfile
- spec/Guardfile
- spec/NOTICE
- spec/README.adoc
- spec/guard.sh
- spec/preview.bat
- spec/preview.sh
- spec/src/main/asciidoc/architecture.asciidoc
> Fix build break after #114 and one typo as mentioned in #114

- api/src/main/java/org/eclipse/microprofile/faulttolerance/Asynchronous.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/Bulkhead.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/CircuitBreaker.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/Fallback.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/Timeout.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/exceptions/FaultToleranceDefinitionException.java
- spec/src/main/asciidoc/asynchronous.asciidoc
- spec/src/main/asciidoc/fallback.asciidoc
> #71 introduce a FaultToleranceDefinitionException

- spec/src/main/asciidoc/configuration.asciidoc
- spec/src/main/asciidoc/relationship.asciidoc
> #108 add hard dependency on config

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/RetryTimeoutTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/BulkheadClientForValidation.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/BulkheadClientForValidationAsynchQueue.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/CircuitBreakerClientForValidationDelay.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/CircuitBreakerClientForValidationFailureRatioNeg.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/CircuitBreakerClientForValidationFailureRatioPos.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/CircuitBreakerClientForValidationReqVol0.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/CircuitBreakerClientForValidationReqVolNeg.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/CircuitBreakerClientForValidationSuccess0.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/CircuitBreakerClientForValidationSuccessNeg.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidBulkheadAsynchQueueTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidBulkheadValueTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidCircuitBreakerDelayTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidCircuitBreakerFailureRatioNegTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidCircuitBreakerFailureRatioPosTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidCircuitBreakerFailureReqVol0Test.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidCircuitBreakerFailureReqVolNegTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidCircuitBreakerFailureSuccess0Test.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidCircuitBreakerFailureSuccessNegTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidRetryDelayDurationTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidRetryDelayTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidRetryJitterTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidRetryMaxRetriesTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidTimeoutValueTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/RetryClientForValidationDelay.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/RetryClientForValidationDelayDuration.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/RetryClientForValidationJitter.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/RetryClientForValidationMaxRetries.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/TimeoutClientForValidation.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retrytimeout/clientserver/RetryTimeoutClient.java
> Add fault tolerance validation tests

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableClient.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableTest.java
> Test MP_Fault_Tolerance_NonFallback_Enabled environment variable

- spec/src/main/asciidoc/relationship.asciidoc
> Add clarification on business method and interceptor binding restrictions

- site.yaml
- spec/src/main/asciidoc/asynchronous.asciidoc
- spec/src/main/asciidoc/configuration.asciidoc
- spec/src/main/asciidoc/relationship.asciidoc
> #127 clarify the annotation configuration

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/ConfigTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableTest.java
> Get config through microprofile config

- spec/src/main/asciidoc/asynchronous.asciidoc
- spec/src/main/asciidoc/circuitbreaker.asciidoc
- spec/src/main/asciidoc/configuration.asciidoc
- spec/src/main/asciidoc/fallback.asciidoc
- spec/src/main/asciidoc/relationship.asciidoc
- spec/src/main/asciidoc/retry.asciidoc
- spec/src/main/asciidoc/timeout.asciidoc
> #129 clarify timeout plus some minor tidy up

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/circuitbreaker/clientserver/CircuitBreakerClientWithRetry.java
> Add maxduration in circuitbreakerretrytest

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadSynchRetryTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/Bulkhead55ClassAsynchronousRetry1Bean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/Bulkhead55ClassAsynchronousRetryBean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/Bulkhead55ClassSynchronousRetry1Bean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/Bulkhead55ClassSynchronousRetryBean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/Bulkhead55MethodAsynchronousRetryBean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/Bulkhead55MethodSynchronousRetryBean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadRapidRetry550MethodSynchBean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadRapidRetry55ClassAsynchBean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadRapidRetry55ClassSynchBean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadRapidRetry55MethodAsynchBean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadRapidRetry55MethodSynchBean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/TestData.java
With these all the bulkhead tests seem to pass reliably now for me so far.
> Gordon tck max duration fix

- NOTICE
- tck/NOTICE
Update notice file with the contributor and their email address
> update notice file

- api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java
> #144 change the default maxDuration value to 1min

- NOTICE
> add a couple of more contributors

- spec/src/main/asciidoc/microprofile-fault-tolerance-spec.asciidoc
> Update spec version

- api/pom.xml
- pom.xml
- spec/pom.xml
- tck/pom.xml
> Switch to 1.1-snapshot

- spec/src/main/asciidoc/retry.asciidoc
> #159 clarify spec

- spec/src/main/asciidoc/fallback.asciidoc
Fixes #177 
Signed-off-by: Andrew Pielage <pandrex247@hotmail.com>
> Update Fallback spec

- spec/src/main/asciidoc/circuitbreaker.asciidoc
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/CircuitBreakerTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/circuitbreaker/clientserver/CircuitBreakerClientDefaultSuccessThreshold.java
> circuit breaker rolling failure window spec and test (issue 197)

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/Utils.java
move the drain action in a finally block to force the submitted tasks to be consumed even in case of failure.
see #198
> drain tasks in Utils.loop in case of Exception

- spec/src/main/asciidoc/timeout.asciidoc
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/AsyncTimeoutTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/asynctimeout/clientserver/AsyncClassLevelTimeoutClient.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/asynctimeout/clientserver/AsyncTimeoutClient.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/util/Connection.java
> @Asynchronous and @Timeout spec and test: issue #185

- spec/src/main/asciidoc/configuration.asciidoc
> #183 - clarify the config on annotation

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/visibility/retry/RetryVisibilityTest.java
> change 5 test expectations

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/TimeoutGlobalConfigTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/TimeoutMethodConfigTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadSynchConfigTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/circuitbreaker/CircuitBreakerConfigGlobalTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/circuitbreaker/CircuitBreakerConfigOnMethodTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/BeanWithRetry.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/ConfigPropertyGlobalVsClassTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/ConfigPropertyGlobalVsClassVsMethodTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/ConfigPropertyOnClassAndMethodTest.java
Solve #182
Signed-off-by: Antoine Sabot-Durand <antoine@sabot-durand.net>
> #microprofile-fault-tolerance-182 Add more configuration based TCK tests

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadSynchConfigTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/ConfigPropertyGlobalVsClassTest.java
> change 1 config test expectation

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/asynctimeout/clientserver/AsyncClassLevelTimeoutClient.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/asynctimeout/clientserver/AsyncTimeoutClient.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/circuitbreaker/CircuitBreakerConfigGlobalTest.java
> fix build breaks

- spec/pom.xml
> #212 update spec pom.xml for pdf and html generation

- README.md
> #207 update readme

- api/src/main/java/org/eclipse/microprofile/faulttolerance/ExecutionContext.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/FallbackTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/fallback/clientserver/SecondStringFallbackHandler.java
> #224 support the exception retrival

- README.adoc
> #207 address review comments

- README.adoc
> #207 more tidy ups

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableAnnotationGloballyTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableAnnotationOnClassTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableAnnotationOnMethodsTest.java
> #252 - fix build break - codestyle errors by #237

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadAsynchRetryTest.java
This is to cope with highly stressed test server.
We allow for the (rare in our batch tests) condition where the server takes ~ 1 second
to do 10 retries that are annotated to have a very tiny delay  - these are done
as fast as possible which is not always fast enough when the (virtual) test servers
experience glitches.
> Tightened assertion in testBulkheadMethodAsynchronousRetry55Trip

- mp_checkstyle_rules.xml
> #190 - reapply the PR done by Carlos

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableAnnotationGloballyTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableAnnotationOnClassTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableAnnotationOnMethodsTest.java
Signed-off-by: Benjamin Confino <benjamic@uk.ibm.com>
> Add AsyncClient to jar

- pom.xml
> #251 - update the description on parent pom

- api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java
> #247 fix typo

- api/pom.xml
- pom.xml
- spec/pom.xml
- tck/pom.xml
> Fix master branch change accident change by release

- spec/src/main/asciidoc/configuration.asciidoc
- spec/src/main/asciidoc/metrics.asciidoc
- spec/src/main/asciidoc/microprofile-fault-tolerance-spec.asciidoc
- spec/src/main/asciidoc/relationship.asciidoc
- spec/src/main/asciidoc/release_notes.asciidoc
add release note for FT 1.1
tidy up the spec to make it readable
> Create release note for FT 1.1 and tidy up the spec

- tck/pom.xml
> fix tck dependency on api

- spec/src/main/asciidoc/configuration.asciidoc
> Grammar fixes for PR #283

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/AsyncTimeoutTest.java
> Do not reset start time in AsyncTimeoutTest

- api/pom.xml
- pom.xml
- spec/pom.xml
- tck/pom.xml
> #294 prepare releasing FT 1.1.1

- api/src/main/java/org/eclipse/microprofile/faulttolerance/Asynchronous.java
- spec/src/main/asciidoc/asynchronous.asciidoc
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/AsynchronousCSTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/AsynchronousTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/asynchronous/AsyncClassLevelClient.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/asynchronous/AsyncClient.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/asynchronous/CompletableFutureHelper.java
Also clarifies behavior when an exception is thrown from an asynch. method and how the value returned from proxy and returned from asynch. invocation relate to each other.
> Issue #110 - Asynchronous with CompletionStage return type

- spec/src/main/asciidoc/fallback.asciidoc
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/FallbackTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/fallback/clientserver/FallbackOnlyClient.java
Apart from the TCK tests I've added a clarification to the documentation.
Signed-off-by: brunobat <bbaptista@tomitribe.com>
> #310 - Add TCK test to validate that @Fallback can be used alone

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/FallbackTest.java
> #fix build break

- spec/src/main/asciidoc/metrics.asciidoc
> Clarify circuitbreaker metrics which report time spent in each state

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/RetryTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClientWithNoDelayAndJitter.java
Signed-off-by: Doychin Bondzhev <doychin@dsoft-bg.com>
> typo fixes

- spec/src/main/asciidoc/circuitbreaker.asciidoc
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/CircuitBreakerTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/circuitbreaker/clientserver/CircuitBreakerClientRollingWindow.java
> #342 clarify the circuit breaker rolling window

- api/src/main/java/org/eclipse/microprofile/faulttolerance/CircuitBreaker.java
- spec/src/main/asciidoc/fallback.asciidoc
> Clarify failon and fallback 240

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/RetryConditionTest.java
Follow on from #371 
After getting our implementation to the point where it could run the tests, I found a few more issues:
* Replace JUnit asserts with TestNG asserts (also requires changing the
order of arguments)
* Fix tests expecting IOException instead of RuntimeException
* Add `@Test` annotation to method which was missing it
* Increase wait time on assertCompleteExceptionally to match
assertCompleteOk
* Improve failure messages produced by assertCompleteExceptionally
> Improvements to RetryConditionTest

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/RetryTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/circuitbreaker/clientserver/CircuitBreakerClientWithRetry.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/circuitbreaker/clientserver/CircuitBreakerClientWithRetryAsync.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClientWithNoDelayAndJitter.java
Fixes for a couple of tests which failed for me during development where investigation showed that there was a fault with the test which could cause intermittent failures.
Further details for each in the commit messages.
> Small test fixes

- api/pom.xml
- pom.xml
- spec/pom.xml
- spec/src/main/asciidoc/release_notes.asciidoc
- tck/pom.xml
> #393 - release prep for FT 2.0

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/BulkheadMetricTest.java
The `BulkheadMetricTest#bulkheadMetricAsyncTest` in the current form assumes the order of calls to an `@Asynchronous` method is the same as the order of checking if the execution can be enqueued for Bulkhead.
This assumption doesn't seem reasonable in asynchronous invocation.
This change adds waiting for queue to be full prior to execution that is expected to fail.
Signed-off-by: Michal Szynkiewicz <michal.l.szynkiewicz@gmail.com>
> BulkheadMetricTest: don't assume the order of async

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/fallbackmethod/FallbackMethodPrivateTest.java
> Package the test bean in the test jar, not the war

- api/src/main/java/org/eclipse/microprofile/faulttolerance/CircuitBreaker.java
Fix checkstyle error introduced by #422
> Fix checkstyle error

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/AsyncFallbackTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/asynchronous/fallback/AsyncFallbackClient.java
> add TCK test for the @Asynchronous @Fallback combination

- tck/pom.xml
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/util/MetricGetter.java
> update the TCK to use MicroProfile Metrics 2.0

- tck/pom.xml
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/util/MetricGetter.java
> switch back to MP Metrics 1.1 and use reflection to also be compatible with MP Metrics 2.0

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/AsyncFallbackTest.java
> add missing assertion in the TCK test for @Asynchronous @Fallback

- tck/pom.xml
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/AsynchronousTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/asynchronous/AsyncClassLevelClient.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/asynchronous/AsyncClient.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/extension/AwaitilityArchiveAppender.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/extension/AwaitilityLoadableExtension.java
- tck/src/main/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
Issue https://github.com/eclipse/microprofile-fault-tolerance/issues/73
> Adding Awaitility to MP TCK

- pom.xml
> exclude javax.el-api

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/Utils.java
Signed-off-by: Ken Finnigan <ken@kenfinnigan.me>
> Make Utils.handleResults() public

- api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java
> specify the meaning of overlapping retryOn and abortOn

- spec/src/main/asciidoc/fault-tolerance-interceptor.asciidoc
> specify how custom throwables are treated

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/RetryExceptionHierarchyTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/exception/hierarchy/E0.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/exception/hierarchy/E0S.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/exception/hierarchy/E1.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/exception/hierarchy/E1S.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/exception/hierarchy/E2.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/exception/hierarchy/E2S.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/exception/hierarchy/RetryService.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/exception/hierarchy/RetryStatus.java
> test @Retry behavior with various exceptions in an inheritance hierarchy

- api/pom.xml
- pom.xml
- spec/pom.xml
- tck/pom.xml
The versions were updated prematurely during the build automation, so I have to change back.
> Micro release

- .gitignore
- api/pom.xml
- api/src/main/java/org/eclipse/microprofile/faulttolerance/Fallback.java
- spec/src/main/asciidoc/fallback.asciidoc
> #417 add fallback enhancement with whitelistand blacklist

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/CircuitBreakerExceptionHierarchyTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/RetryExceptionHierarchyTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/circuitbreaker/exception/hierarchy/CircuitBreakerService.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/exception/hierarchy/E0.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/exception/hierarchy/E0S.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/exception/hierarchy/E1.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/exception/hierarchy/E1S.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/exception/hierarchy/E2.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/exception/hierarchy/E2S.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/exception/hierarchy/package-info.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/exception/hierarchy/RetryService.java
Check that `failOn` and `skipOn` are implemented correctly.
Fixes #418
> Add CB exception hierarchy tests

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/FallbackExceptionHierarchyTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/fallback/exception/hierarchy/FallbackService.java
> #417 add tests on fallback skipOn and applyOn

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/FallbackExceptionHierarchyTest.java
Fixed a typo where 'InvokeServiceC' was calling 'ServiceB' instead.
> Fix FallbackExceptionHierarchyTest.java

- pom.xml
> Update maven plugins to their latest versions

- pom.xml
> #487 - fix Jenkins build

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadAsynchRetryTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadAsynchTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadFutureTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadSynchConfigTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadSynchRetryTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadSynchTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/Checker.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/ParrallelBulkheadTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/TestData.java
Adding awaitility when to the first test refactor
issue #271
Signed-off-by: Carlos Andres De La Rosa kusanagi12002@gmail.com
> Adding awaitility to Bulkhead Tests First refactor

- spec/src/main/asciidoc/asynchronous.asciidoc
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadFutureTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/FutureChecker.java
Resolves #425.
Supersedes #426.
> relax the requirements on Future implementations

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/RetryConditionTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/asyncretry/clientserver/AsyncRetryClient.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/util/AsyncCallerExecutor.java
Signed-off-by: Bruno <brunobat@gmail.com>
> #416 - executor for tests

- api/pom.xml
- pom.xml
- tck/pom.xml
> move from Java EE 8 to Jakarta EE 8 specification artifacts

- spec/src/main/asciidoc/circuitbreaker.asciidoc
I've moved around the text a bit so that the examples are next to the
part of the spec that they're demonstrating.
> Update the CircuitBreaker spec with more examples

- spec/src/main/asciidoc/metrics.asciidoc
> improve retry metrics specification

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/CircuitBreakerConfigBean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/CircuitBreakerConfigTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/CircuitBreakerSkipOnConfigTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/ConfigAnnotationAsset.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/FallbackApplyOnConfigTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/FallbackConfigBean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/FallbackConfigTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/FallbackSkipOnConfigTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/TestConfigExceptionA.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/TestConfigExceptionB.java
* Test that Fallback applyOn and skipOn can be configured
* Test that CircuitBreaker skipOn can be configured
For #407
> Add configuration tests for parameters new in 2.1

- api/pom.xml
- pom.xml
- tck/pom.xml
This reverts commit 8dc5b0f75b515c8535e0954deb975c25d2caa9dc.
> Revert "move from Java EE 8 to Jakarta EE 8 specification artifacts"

- api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/Timeout.java
> #485 add javadoc

- spec/src/main/asciidoc/release_notes.asciidoc
> release notes for 2.1

- spec/src/main/asciidoc/release_notes.asciidoc
I was late with my review on #447, add two other issues which have gone into 2.1.
> Add #274 and #484 to the release notes for 2.1

- pom.xml
> #487 fix gpg failure for Jenkins build

- api/src/main/java/org/eclipse/microprofile/faulttolerance/FallbackHandler.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/util/MetricGetter.java
> Resolve JDK 13 generating Javadoc build issue

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/util/ConcurrentExecutionTracker.java
> Make timeout for concurrent execution tracker configurable

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/TimeoutUninterruptableTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/timeout/clientserver/UninterruptableTimeoutClient.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/util/TCKConfig.java
> Fixed TimeoutUninterruptableTest scaling issue with TCKConfig baseMultiplier

- api/pom.xml
- pom.xml
- tck/pom.xml
This reverts commit f77cb7c182bdcc5a713d4f0f9e8e46363a879fe8.
Resolves #467.
> Revert "Revert "move from Java EE 8 to Jakarta EE 8 specification artifacts""

- api/src/main/java/org/eclipse/microprofile/faulttolerance/Bulkhead.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/CircuitBreaker.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/Fallback.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java
- api/src/main/java/org/eclipse/microprofile/faulttolerance/Timeout.java
> for each annotation, add a listing of all atributes at the end of main javadoc

- api/pom.xml
> #494 update osgi versioning dependency scope

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/CircuitBreakerMetricTest.java
> Configurable timeouts in CircuitBreakerMetricTest

- api/bnd.bnd
- api/pom.xml
- pom.xml
> #530 update bnd version and baseline version

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/CircuitBreakerMetricTest.java
> FT 2.0: Configurable timeouts in CircuitBreakerMetricTest

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/CircuitBreakerMetricTest.java
> FT 2.1: Configurable timeouts in CircuitBreakerMetricTest

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/CircuitBreakerTimeoutTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/RetryTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/circuitbreaker/clientserver/CircuitBreakerClientWithTimeout.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClientWithDelay.java
> [FT 2.0] Add timeout configuration to RetryTest and CircuitBreakerTimeoutTest

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/CircuitBreakerTimeoutTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/RetryTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/circuitbreaker/clientserver/CircuitBreakerClientWithTimeout.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClientWithDelay.java
> [FT 2.1] Add timeout configuration to RetryTest and CircuitBreakerTimeoutTest

- spec/src/main/asciidoc/metrics.asciidoc
> fix a couple of typos in the metrics specification

- spec/src/main/asciidoc/optional-container-integration.asciidoc
- spec/src/main/asciidoc/relationship.asciidoc
> replace Java EE references with Jakarta EE references

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/FallbackConfigBean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/FallbackConfigTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/FallbackHandlerA.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/FallbackHandlerB.java
> 407: add tck for fallback config

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/BulkheadConfigBean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/BulkheadConfigTest.java
> Add tests for configuration of Bulkhead

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/CircuitBreakerConfigBean.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/CircuitBreakerConfigTest.java
- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/util/Exceptions.java
> add TCK tests for configuring @CircuitBreaker attributes

- tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/TimeoutConfigTest.java
> Fix TimeoutConfigTest bug

- .github/ISSUE_TEMPLATE/00-use-case.md
- .github/ISSUE_TEMPLATE/10-clarification.md
- .github/ISSUE_TEMPLATE/20-bug-report.md
- .github/ISSUE_TEMPLATE/30-impl-proposal.md
- .github/ISSUE_TEMPLATE/30-spec-change-proposal.md
- .github/workflows/build.yml
> 566: enable github actions and add some issue templates

- .github/ISSUE_TEMPLATE/00-use-case.md
- .github/ISSUE_TEMPLATE/10-clarification.md
- .github/ISSUE_TEMPLATE/20-bug-report.md
- .github/ISSUE_TEMPLATE/30-spec-change-proposal.md
> 566 - github template - fix comments

- .github/ISSUE_TEMPLATE/00-use-case.md
- .github/ISSUE_TEMPLATE/10-clarification.md
- .github/ISSUE_TEMPLATE/20-bug-report.md
- .github/ISSUE_TEMPLATE/30-spec-change-proposal.md
- pom.xml
> remove copyright from issue templates

- .github/ISSUE_TEMPLATE/00-use-case.md
- .github/ISSUE_TEMPLATE/30-spec-change-proposal.md
Apparently blank lines causes template not to function.
> remove blank lines from issue templates

- .github/workflows/build.yml
> Update the build workflow to setup java at v1

- spec/pom.xml
- spec/src/main/asciidoc/license-efsl.adoc
> improve the way to handle copyright year

- spec/src/main/asciidoc/metrics.asciidoc
Signed-off-by: Jan Bernitt <jaanbernitt@gmail.com>
> Adds section on metrics registration

- pom.xml
- tck/pom.xml
> Move up the dependency version for final release

- api/pom.xml
- pom.xml
- spec/pom.xml
- tck/pom.xml
This reverts commit 7ed5fefa6603f5a77303144cae6d94f5f48ce5ff.
> Revert "[maven-release-plugin] prepare release 3.0"

- api/src/main/java/org/eclipse/microprofile/faulttolerance/package-info.java
- tck/pom.xml
Consume the latest dependencies on MP Config and Metrics
Update the package version as the annotation import has been update from javax to jakarta
> Consume the latest dependencies

- spec/src/main/asciidoc/architecture.asciidoc
The Interceptor spec URL was incorrect.
> Corrected Interceptor Specification URL

- pom.xml
- tck/pom.xml
> prepare for MP 6

- spec/pom.xml
- spec/src/main/asciidoc/release_notes.asciidoc
Fix a broken link in the spec
Update the build so that it fails if it detects a broken internal link.
> Fix broken link in spec

- pom.xml
- spec/src/main/asciidoc/license-efsl.adoc
License text from https://www.eclipse.org/legal/adoc/efsl-1.1.adoc
> Update spec license to EFSL v1.1
