eclipse/microprofile-fault-tolerance

api/src/main/java/org/eclipse/microprofile/fault/tolerance/inject/Timeout.java
- rename annotation to Timeout
- rename timeOut() to value()
- rename timeOutUnit() to unit()
Signed-off-by: Martin Kouba <mkouba@redhat.com>
See also https://github.com/eclipse/microprofile-fault-tolerance/issues/13#issuecomment-308125929
=> Make TimeOut annotation easier to read and use

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadAsynchTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadSynchTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/Utils.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BackendTestDelegate.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadClassAsynchronous10Bean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadClassAsynchronous3Bean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadClassAsynchronousDefaultBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadClassAsynchronousQueueingBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadClassSemaphore10Bean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadClassSemaphore3Bean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadClassSemaphoreDefaultBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadMethodAsynchronous10Bean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadMethodAsynchronous3Bean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadMethodAsynchronousDefaultBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadMethodAsynchronousQueueingBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadMethodSemaphore10Bean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadMethodSemaphore3Bean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadMethodSemaphoreDefaultBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadTestBackend.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/Checker.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/ParrallelBulkheadTest.java
I had had a "-Drat.skip=true" in my alias that ran the test cycle,
bare 'mvn clean install' did show previous rat check error with new 
header and now passes with this PR which reverts the headers.
Apologies for the inconvenience and my mistake.
=> Updated headers to pass rat check

spec/src/main/asciidoc/configuration.asciidoc
Signed-off-by: Tom Evans <tevans@uk.ibm.com>
=> Issue 94 - use dollar rather than colon in config keys

api/pom.xml, pom.xml, spec/pom.xml, tck/pom.xml
According to the [Contributing guidelines in the Wiki](https://wiki.eclipse.org/MicroProfile/ContributingGuidelines#Deliverable_group_and_artifact_naming_convention) and also according to the practice used with MP Config, I suggest that maven group of all artifacts is changed to `org.eclipse.microprofile.fault-tolerance`, even for the parent. Using `fault-tolerance` seems better to me than `fault.tolerance`, because it implies that both words together form a single name of a feature, rather than a nested feaure.
I also fixed the version of parent to 1.0-SNAPSHOT to be in line with the version of other parents to make it easier to do a release with maven release plugin later.
=> Suggesting alignment of maven artifact groups

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadAsynchRetryTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadAsynchTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadFutureTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadSynchRetryTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadSynchTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/Utils.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/Bulkhead55MethodSynchronousRetryBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/Checker.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/FutureChecker.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/ParrallelBulkheadTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/TestData.java
Here are some test improvements. Adding the use of a CountDownLatch and removing the reusing of static data between tests to make the tests more reliable.
=> Gordon tck bulkhead tests timing issues1

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadAsynchRetryTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadAsynchTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadFutureTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadSynchRetryTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadSynchTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/FutureChecker.java
The tests were throwing errors if an application level Future had methods other than the
gets called - this was wrong.
=> Fix wrong assumption in Bulkhead Future tests

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/CircuitBreakerTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/Misc.java
> :warning: __by correcting the behavior of tests this commit introduces changes compared to initial TCK version__ :warning: 
as discussed in #188 & #136 the status change of a circuit into OPEN state should work in a window of `requestVolumeThreshold` calls and should match `failureRatio`. There's no need to wait for `requestVolumeThreshold` failed calls.
I separated the PR in 2 commits. The first one adresses really the issue, the second one clarifies & unifies a bit some expectations on the test file I worked on so by being more consistent it is easier to read/understand the tests.
I can of course squash/rebase both commits or remove the latest one if required.
=> make failureRatio work into requestVolumeThreshold consecutive window calls

pom.xml, tck/pom.xml, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/illegalConfig/IncompatibleFallbackMethodTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/illegalConfig/IncompatibleFallbackMethodWithArgsTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/illegalConfig/IncompatibleFallbackPolicies.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/illegalConfig/IncompatibleFallbackTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidBulkheadAsynchQueueTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidBulkheadValueTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidCircuitBreakerDelayTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidCircuitBreakerFailureRatioNegTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidCircuitBreakerFailureRatioPosTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidCircuitBreakerFailureReqVol0Test.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidCircuitBreakerFailureReqVolNegTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidCircuitBreakerFailureSuccess0Test.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidCircuitBreakerFailureSuccessNegTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidRetryDelayDurationTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidRetryDelayTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidRetryJitterTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidRetryMaxRetriesTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidTimeoutValueTest.java
as explained in the gitter & in [google groups](https://groups.google.com/forum/#!topic/microprofile/HI0NgS4A5Ag), to let all container a chance to run the tests that expect `@ShouldThrowException` a move to _arquillian-core-1.1.14.Final_ is required together with an enhancement of all tests using `@ShouldThrowException`.
This PR should not hurt (but it is to be verified) the embedded arquillian containers, still offering a chance to the remote ones to support the `@ShouldThrowException` tests.
Issues references:
- fault-tolerance issue: #200
- arquillian-core new feature: arquillian/arquillian-core#135
- enhancement in wildfly-arquillian: wildfly/wildfly-arquillian#116
=> update arquillian-core & support testable when ShouldThrowException is used

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadSynchRetryTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/Bulkhead55ClassSynchronousRetryBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadRapidRetry50MethodSynchBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadRapidRetry550MethodSynchBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadRapidRetry55ClassSynchBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadRapidRetry55MethodSynchBean.java
Some of the synchronous tests are annotated with `@Asynchronous`, making them, well, not synchronous.
These tests also already submit themselves to an executor to simulate multiple simultaneous calls, so with this annotation present the tests are being submitted to an executor, to be then be submitted to a second executor.
=> Remove @Asynchronous annotation from sync tests

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadAsynchRetryTest.java
- TestData.check() must not be invoked before async wrappers are executed
- resolves #232
=> Fix BulkheadAsynchRetryTest#testBulkheadMethodAsynchronousRetry55Trip()

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadFutureTest.java
This pull request is to resolve: 
https://github.com/OpenLiberty/open-liberty/issues/2958
where we see the test case failing on the odd occasion.
fixes OpenLiberty/open-liberty#2958
=> Increased robustness of testBulkheadClassAsynchFutureDoneWithoutGet test

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableAnnotationGloballyTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableAnnotationOnClassTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableAnnotationOnMethodsTest.java
The connection class is used by AsyncClient in the tests in the disableEnv package. Without it the test fails with an injection error.
=> 263 Add Connection to disableEnv test jars

spec/src/main/asciidoc/configuration.asciidoc, spec/src/main/asciidoc/metrics.asciidoc, spec/src/main/asciidoc/microprofile-fault-tolerance-spec.asciidoc, tck/pom.xml, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/AsynchronousTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/AllMetricsBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/AllMetricsTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/BulkheadMetricBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/BulkheadMetricTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/CircuitBreakerMetricBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/CircuitBreakerMetricTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/ClassLevelMetricBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/ClassLevelMetricTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/MetricsDisabledTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/RetryMetricBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/RetryMetricTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/TimeoutMetricBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/TimeoutMetricTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/util/AsyncCaller.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/util/Exceptions.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/util/MetricComparator.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/util/MetricGetter.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/util/TestException.java
=> Integration with Microprofile Metrics

spec/src/main/asciidoc/metrics.asciidoc, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/AllMetricsTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/FallbackMetricBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/FallbackMetricHandler.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/FallbackMetricTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/MetricsDisabledTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/util/MetricGetter.java
Add a new counter named `ft.<name>.fallback.calls.total` for how many times a fallback method or handler is called.
Currently, there's no way to find this out. Also, with the way `ft.<name>.invocations.failed.total` is specified, that counter will only increment for a method annotated with `@Fallback` if the fallback method also throws an exception.
This metric gives you a better idea of how often your main logic fails, as well as allowing you to see if your fallback itself is failing.
For #234
=> Metrics add fallback counter

spec/src/main/asciidoc/metrics.asciidoc, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/ClashingNameBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/ClashingNameTest.java
I'm not sure how specific we should be here.
We could go all the way and explain how each metric type should be combined - in most cases this is a simple sum. We could then add tests to ensure that metrics are combined correctly in all cases.
From an implementation point of view, this isn't too arduous, though some additional work would be required to combine gauges.
However, I'm not sure how valuable combining metrics is for the user. Essentially we're just trying to do something sensible if this situation happens so for the moment, I've just added a simple test which ensures that the implementation doesn't throw an exception and increments the basic invocation metric.
=> State what happens when metric names clash

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/illegalConfig/IncompatibleFallbackMethodTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/illegalConfig/IncompatibleFallbackMethodWithArgsTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/illegalConfig/IncompatibleFallbackPolicies.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/illegalConfig/IncompatibleFallbackTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidBulkheadAsynchQueueTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidBulkheadValueTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidCircuitBreakerDelayTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidCircuitBreakerFailureRatioNegTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidCircuitBreakerFailureRatioPosTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidCircuitBreakerFailureReqVol0Test.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidCircuitBreakerFailureReqVolNegTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidCircuitBreakerFailureSuccess0Test.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidCircuitBreakerFailureSuccessNegTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidRetryDelayDurationTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidRetryDelayTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidRetryJitterTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidRetryMaxRetriesTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidTimeoutValueTest.java
As discussed in #211 it is not possible for an implementor of DeployableContainer
to both throw an exception from deploy AND give arquillian-core the metadata it needs to make
a test testable (for example to get the context endpoints needed to speak to communicate with the test on the container). 
So TCK tests with ShouldThrowException( ... testable = true ) could never be testable on a
arquillian container and indeed the current arquillian core will NPE. There is no way to code
round this in the Container code with the current DeployableContainer interface.
This can be seen in 
wildfly - https://issues.jboss.org/browse/WFARQ-36 and
liberty - #211  ( and OpenLiberty/open-liberty#3100 )
=> Remove testable=true from ShouldThrowException annotations

spec/src/main/asciidoc/configuration.asciidoc, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableAnnotationClient.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableAnnotationGloballyEnableOnClassDisableOnMethod.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableAnnotationGloballyEnableOnClassTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableAnnotationGloballyEnableOnMethodTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableAnnotationGloballyTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableAnnotationOnClassEnableOnMethodTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableAnnotationOnClassTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableConfigAsset.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/AllMetricsTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/BulkheadMetricBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/BulkheadMetricTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/CircuitBreakerMetricBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/CircuitBreakerMetricTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/ClassLevelMetricBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/ClassLevelMetricTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/FallbackMetricBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/FallbackMetricHandler.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/FallbackMetricTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/MetricsDisabledTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/RetryMetricTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/TimeoutMetricTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/util/Exceptions.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/util/ConcurrentExecutionTracker.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/util/Packages.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/util/TestException.java
Allow annotations to be explicitly enabled via config as well as being disabled.
This allows a Fault Tolerance annotation to be disabled globally, but then enabled for a specific class or method.
Add TCKs to test this behaviour.
This is to address #266 
This includes and completes the work that @Emily-Jiang started under #270
=> Allow annotations to be explicitly enabled via config

spec/src/main/asciidoc/configuration.asciidoc
when using `MP_Fault_Tolerance_NonFallback_Enabled` together with other individual configuration, the property `MP_Fault_Tolerance_NonFallback_Enabled` has the lowest priority.
=> Add spec changes to clarify the configuration order

spec/src/main/asciidoc/metrics.asciidoc
`ft.<name>.fallback.calls.total` is a `Counter`, not a `Gauge`.
The TCK already tests that it is a `Counter` and does not need changed.
=> Fix mistake in the metrics integration spec

api/bnd.bnd, api/pom.xml, api/src/main/java/org/eclipse/microprofile/faulttolerance/ExecutionContext.java, api/src/main/java/org/eclipse/microprofile/faulttolerance/package-info.java
update package version and use the bnd baseline to verify
update the cdi dependency to work with both cdi 1.2 and cdi 2.0
=> prepare release - fix the api version and use baseline to verify

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/ClashingNameTest.java
clashingNameTest was checking that the invocation counter had been
incremented, without waiting for the Asynchronous method to return.
Usually this passes for me as the `doWork()` methods are very simple, but occasionally it fails because the async method hasn't run by the time we check the counter.
The incorrect test is in the released 1.1 TCK. I'm not sure what we need to do about that.
=> Fix race condition in ClashingNameTest.testClashingName

spec/src/main/asciidoc/configuration.asciidoc
This spec section was accidentally removed previously.
Fixes #300
=> Reinstate metrics integration configuration spec

api/src/main/java/org/eclipse/microprofile/faulttolerance/Asynchronous.java, spec/src/main/asciidoc/asynchronous.asciidoc, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/AsynchronousCSTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/AsynchronousTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/asynchronous/AsyncClassLevelClient.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/asynchronous/AsyncClient.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/asynchronous/CompletableFutureHelper.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/AsynchronousClientForValidationClass.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/AsynchronousClientForValidationMethod.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidAsynchronousClassTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/InvalidAsynchronousMethodTest.java
Fixes on top of #267 in response to issues raised in that PR.
Note that at the moment, this PR includes everything in #267. If #267 is merged, I'll rebase this so it only includes my changes.
=> Small fixes for Async with CompletionStage

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/util/Packages.java
fixes #317
Signed-off-by: Antoine Sabot-Durand <antoine@sabot-durand.net>
=> TCK: Packages.METRIC_UTILS may be null - causes a lot of tests to fail

spec/src/main/asciidoc/asynchronous.asciidoc, spec/src/main/asciidoc/bulkhead.asciidoc, spec/src/main/asciidoc/circuitbreaker.asciidoc, spec/src/main/asciidoc/retry.asciidoc, spec/src/main/asciidoc/timeout.asciidoc
Adds detail about how fault tolerance annotations interact and adds some
detail to @Asynchronous which was previously only present in the
Javadoc.
Addresses #291
=> Specify interactions between annotations more completely

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/BulkheadMetricTest.java
Replace @AfterTest by @After Method stop the hanging and fix #329
Signed-off-by: Antoine Sabot-Durand <antoine@sabot-durand.net>
=> Fix #329 TCK: BulkheadMetricTest is hanging when failing

api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java, spec/src/main/asciidoc/retry.asciidoc, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/RetryTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClientWithNoDelayAndJiter.java
Test to make sure the minimum effective delay is 0, even when jitter > delay.
Tested this in Safegard... It implements Jitter after all. These were the effective delays, in ms:
[1, 0, 0, 1, 0, 0, 28, 279, 0, 86, 19, 0, 370, 360, 142, 325, 1, 0, 200, 350, 1, 369, 0, 1, 0, 0, 0, 0, 43, 0, 0, 0, 51, 230, 37, 0, 1, 87, 0, 149, 70]
Signed-off-by: brunobat <bbaptista@tomitribe.com>
=> Issue #312 - Retry: What happens when delay is less than jitter? 

mp_checkstyle_rules.xml, pom.xml, tck/src/test/java/org/eclipse/microprofile/fault/tolerance/tck/visibility/retry/PureJ2SERetryVisibilityTest.java
https://github.com/eclipse/microprofile-fault-tolerance/issues/252
CheckStyle Rules moved to an external configuration file to allow
maintain these rules in an easy and centralized way.
This file can be used by the CI server to validate the project code style
Signed-off-by: carlos de la rosa <kusanagi12002@gmail.com>
=> CheckStyle Rules moved to an external configuration file issue 252

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/BulkheadMetricTest.java
Waiting for 3s was longer than necessary
Fixes #337 
=> Shorten wait time on BulkheadMetricTest

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/RetryTest.java
One of the test classes was missing which caused the deployed application to fail to start.
=> Add test class to RetryTest deployment

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadFutureTest.java
We see a small percentage of the same error as #242 on this test on unusually slow hardware
or virtual hosts where something happens to create a moment of slowness.
This fix is the same safety net as 242 just to ensure the test is not brittle to such
platform treacle slow issues.
=> Added same fix as issue 242 to testBulkheadMethodAsynchFutureDoneWithoutGet

spec/src/main/asciidoc/timeout.asciidoc
This avoids the possibility that a later call to `Thread.interrupted()`
returns `true` due to a timeout in an earlier method call.
Fixes #322
=> Spec that interrupted status must be cleared after timeout

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/AsyncCancellationTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/asynchronous/AsyncCancellationClient.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/AbstractBulkheadTask.java
Tests for calling `Future.cancel()` on a method annotated with `@Asynchronous`
Fixes #366
=> Add cancellation TCKs

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/AsyncTimeoutTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClientWithDelay.java
As per the java documentation nanoTime is the appropriate method for checking the duration of a running	thread. Using nanoTime will also protect the tests from any changes to the system clock while the tck is running.
Signed-off-by: Benjamin Confino <benjamic@uk.ibm.com>
=> 373 - Change system time to use nanoseconds

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/AsyncTimeoutTest.java
This happens due to the new Duration usage. Fix missing import, compare operations and line length.
Signed-off-by: brunobat <bbaptista@tomitribe.com>
=> Fix compilation failure 

tck/pom.xml, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/interceptor/xmlInterceptorEnabling/EarlyFtInterceptor.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/interceptor/xmlInterceptorEnabling/FaultToleranceInterceptorEnableByXmlTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/interceptor/xmlInterceptorEnabling/InterceptorComponent.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/interceptor/xmlInterceptorEnabling/LateFtInterceptor.java
https://github.com/eclipse/microprofile-fault-tolerance/issues/313
New test added to validate the CDI interceptors against FT interceptors
when the CDI interceptors are activated using xml configuration instead
using @Priority annotation configuration
Signed-off-by: carlos de la rosa <kusanagi12002@gmail.com>
=> Test CDI (Using XML configuration) and FT interceptors ordering

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/AsyncTimeoutTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClientWithDelay.java
I've used Duration where possible to avoid having the same mistake
happen again.
Also fix RetryClientWithDelay so that it records the delay between
subsequent executions correctly.
Fixes #373
I also came across an issue where we were measuring times incorrectly in `testAsyncClassLevelTimeout` so I've fixed that too.
=> Fix tests where ms had been changed to ns inconsistently

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/interceptor/ftPriorityChange/EarlyFtInterceptor.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/interceptor/ftPriorityChange/FaultToleranceInterceptorPriorityChangeAnnotationConfTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/interceptor/ftPriorityChange/FaultToleranceInterceptorPriorityChangeXmlConfTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/interceptor/ftPriorityChange/InterceptorComponent.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/interceptor/ftPriorityChange/LateFtInterceptor.java
FT interceptor priority issue 313
https://github.com/eclipse/microprofile-fault-tolerance/issues/313
New tests added to validate the CDI interceptors against FT interceptor
when the FT interceptor priority is changed and the CDI interceptors
are injected to the context using xml or annotation base configuration.
Signed-off-by: carlos de la rosa <kusanagi12002@gmail.com>
=> Test CDI and FT interceptors ordering changing FT interceptor priority

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/ZeroRetryJitterTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClientForZeroJitter.java
Incorrectly written code can lead to error during execution if jitter = 0 is not properly processed.
Signed-off-by: Doychin Bondzhev <doychin@dsoft-bg.com>
=> Add test to validate proper execution when jitter = 0

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/AsyncCancellationTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/ZeroRetryJitterTest.java
Replace with testng or hamcrest assertions
Note that the usage of junit `@After` in `TestAsyncCancellationTest` is actually a bug which will result in one of the test execution tasks never completing because the cleanup logic will not be run.
=> Remove incorrect uses of junit

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClientWithNoDelayAndJitter.java
Here, we're actually measuring the retry delay, plus the execution time
of the method and the time taken for any Fault Tolerance processing, so
add a small margin.
=> Add a small margin to expected retry delays

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/TimeoutUninterruptableTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/timeout/clientserver/UninterruptableTimeoutClient.java
Unnecessarily tight time bounds can cause spurious failures in case of
unexpected pauses (e.g. CG, jit, CPU time starvation)
TimeoutUninterruptableTest had quite tight bounds on how quickly the
TimeoutException is returned. However, what's important in this test is
that the TimeoutException is returned before the method has returned so
the bounds can be loosened without invalidating the test.
This sort of problem should be resolved properly by making the timeouts configurable under #399, this is a stop-gap measure to reduce the chance of spurious failures when running the 2.0 TCK.
Also change calls which would wait forever so that the test doesn't hang if the implementation does not work correctly.
=> Widen the timing bounds on TimeoutUninterruptableTest

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadAsynchRetryTest.java
=> #409 fix thread ordering in BulkheadAsynchRetryTest.testRetriesJoinBackOfQueue

spec/src/main/asciidoc/metrics.asciidoc, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/CircuitBreakerMetricBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/CircuitBreakerMetricTest.java
Resolves #419
In case `@CircuitBreaker(failOn = {IllegalArgumentException.class})`
is defined and the guarded method throws e.g. `IllegalStateException`,
the circuit breaker treats it as success and therefore the
`circuitbreaker.callsSucceeded.total` metric needs to be incremented.
This commit adjusts the spec to make this clear, and also adds
a TCK test for this behavior.
=> clarify circuit breaker metrics

api/src/main/java/org/eclipse/microprofile/faulttolerance/CircuitBreaker.java
The JavaDoc of `@CircuitBreaker` is IMO lacking a bit clarity. I saw some confusion around the delay period when exactly that is taken into consideration. I've added the documentation of the circuit breaker states, clarified, and cleaned-up the individual annotation method docs.
=> Enhanced circuit breaker API docs

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/AsynchronousCSTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/AsynchronousTest.java
AfterTest is executed at the end of the whole test run. We want this
cleanup logic to run after each test method.
=> Change @AfterTest to @AfterMethod in async tests

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/RetryConditionTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClientRetryOn.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/exceptions/RetryChildException.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/exceptions/RetryParentException.java
configured 2 lists of exceptions retryOn(whitelist)
and abortOn(blacklist) in the same annotation in this case retry
https://github.com/eclipse/microprofile-fault-tolerance/issues/418
Signed-off-by: Carlos Andres De La Rosa <kusanagi12002@gmail.com>
=> Adding more retry tests to see how is working whitelist and blacklist together in the same annotation

spec/src/main/asciidoc/retry.asciidoc, spec/src/main/asciidoc/timeout.asciidoc
Avoid giving the impression that running retries on the same thread is
valid in all cases.
Fixes #424
=> Add a clarifying note on running retries on the same thread

api/src/main/java/org/eclipse/microprofile/faulttolerance/CircuitBreaker.java, api/src/main/java/org/eclipse/microprofile/faulttolerance/package-info.java, spec/src/main/asciidoc/circuitbreaker.asciidoc
Add the `skipOn` parameter to Circuit Breaker
Update the spec and javadoc to specify the meaning of `skipOn` and how `failOn` and `skipOn` interact.
We still need TCKs for this. I'll likely base them on @Ladicek's tests in #440.
For #418
=> Add skipOn to CircuitBreaker

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/circuitbreaker/clientserver/CircuitBreakerClientWithSyncBulkhead.java
This bean is called asynchronously and there's no requirement for the
request scope to be active on an async thread.
=> Make CircuitBreakerClientWithSyncBulkhead Dependent

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/circuitbreaker/clientserver/CircuitBreakerClientWithSyncBulkhead.java
This bean is called asynchronously and there's no requirement for the
request scope to be active on an async thread.
This is a port of #463 to the master branch
=> Make CircuitBreakerClientWithSyncBulkhead Dependent (master)

spec/src/main/asciidoc/retry.asciidoc
This is already specified in the `@Retry` javadoc. This commit
adds the same wording to the specification text.
=> specify the meaning of overlapping retryOn and abortOn

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/ConfigTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/RetryTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/TimeoutTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/TimeoutUninterruptableTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/clientserver/ConfigClient.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClientWithNoDelayAndJitter.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/timeout/clientserver/TimeoutClient.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/timeout/clientserver/UninterruptableTimeoutClient.java
* Remove inactive config code from `TimeoutTest`
* Corrections in `ConfigTest`
* Add configuration to TimeoutInterruptableTest`
* relax timing checks in `testRetryWithNoDelayAndJitter`
=> Further timeout configuration improvements

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/CircuitBreakerRetryTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/TimeoutMetricTest.java
When the `microprofile-config.properties` file, generated by
`ConfigAnnotationAsset`, is put into `META-INF`, the archive
needs to be a JAR. That JAR can then be put into a WAR.
All tests that use `ConfigAnnotationAsset` follow this pattern,
except `TimeoutMetricTest`, where the file is put directly
into the WAR. From there, it can't be read, as `META-INF`
inside a WAR is not on classpath.
This commit fixes `TimeoutMetricTest` to follow the same
pattern: put everything into a JAR, and that JAR into a WAR.
Resolves #496.
=> fix the timeout metrics test

spec/src/main/asciidoc/asynchronous.asciidoc, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/BulkheadAsynchTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadCompletionStageBean.java
Update the spec to make clear that the Bulkhead doesn't consider the method to be complete until the returned completion stage completes.
Add TCK tests to assert this.
Fixes #484
=> Specify behaviour of Async Bulkhead with CompletionStage

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/CircuitBreakerExceptionHierarchyTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/circuitbreaker/exception/hierarchy/CircuitBreakerService.java
Change the CircuitBreakerExceptionHierarchyTest to use a different
service method for each test.
This requires the service method to be replicated lots of times, but
allows the lifetime of the circuit breaker to be tied to the method
itself rather than to the bean instance.
=> Use separate methods in CircuitBreakerExceptionHierarchyTest

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/bulkhead/clientserver/BulkheadCompletionStageBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/CircuitBreakerConfigBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/FallbackConfigBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/fallback/exception/hierarchy/FallbackService.java
This is to make sure the TCK can pass on Quarkus, which requires
all beans to have bean-defining annotations.
Resolves #508.
=> add bean-defining annotations to beans in TCK

api/src/main/java/org/eclipse/microprofile/faulttolerance/Asynchronous.java, api/src/main/java/org/eclipse/microprofile/faulttolerance/Bulkhead.java, api/src/main/java/org/eclipse/microprofile/faulttolerance/CircuitBreaker.java, api/src/main/java/org/eclipse/microprofile/faulttolerance/ExecutionContext.java, api/src/main/java/org/eclipse/microprofile/faulttolerance/Fallback.java, api/src/main/java/org/eclipse/microprofile/faulttolerance/FallbackHandler.java, api/src/main/java/org/eclipse/microprofile/faulttolerance/Retry.java, api/src/main/java/org/eclipse/microprofile/faulttolerance/Timeout.java
Some of these changes will be up for discussion, as some are preferences rather than corrections.
I've tried to follow some standards, such as:
* no capitals after @return's
* colons before listed items
*  consistent full stops, excluding:
*  listed items which are not sentences
* sentences following @return's
=> Typo and grammar corrections

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/AllMetricsBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/AllMetricsTest.java
Fixes #519 
Updated AllMetricsBean: 
* Increased the Timeout duration to 1 minute
* Scaled all the FT values  with the the TCKConfig baseMultiplier using the autoscaleMethod
=> Updated AllMetricsBean

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/TimeoutUninterruptableTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/AllMetricsBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/AllMetricsTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/timeout/clientserver/UninterruptableTimeoutClient.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/util/ConcurrentExecutionTracker.java
Introduces the following PR's:
#520 - Updated AllMetricsBean
#517 - TimeoutUninterruptableTest scaling issue fix
#511 - Make concurrent execution tracker configurable
This branch did not work for Java 13 for me, due to a JDK 13 generating Javadoc build issue #513 , not yet being merged into this branch.
=> Add TCK fixes 2.1.x

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/TimeoutUninterruptableTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/AllMetricsBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/AllMetricsTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/timeout/clientserver/UninterruptableTimeoutClient.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/util/ConcurrentExecutionTracker.java
Introduces the following PR's:
#520 - Updated AllMetricsBean
#517 - TimeoutUninterruptableTest scaling issue fix
#511 - Make concurrent execution tracker configurable
This branch did not work for Java 11 or 13 for me.
Only Java 8:
```
josephcass$ java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
Eclipse OpenJ9 VM (build openj9-0.18.1, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20200122_439 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - 8cf8a30581 based on jdk8u242-b08)```
=> Add TCK fixes 2.0.x

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/BulkheadMetricBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/BulkheadMetricTest.java
Have `BulkheadMetricTest` use `Future.get(timeout)` rather than `Future.get()`
to avoid cases where the test could hang instead of failing.
Backport of #541 for #538
=> [2.1.x] Prevent BulkheadMetricTest hanging

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/BulkheadMetricBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/BulkheadMetricTest.java
Have `BulkheadMetricTest` use `Future.get(timeout)` rather than `Future.get()`
to avoid cases where the test could hang instead of failing.
This also wants backporting to the 2.1.x branch.
Fixes #538
=> Prevent BulkheadMetricTest hanging

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/CircuitBreakerTimeoutTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/RetryTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/circuitbreaker/clientserver/CircuitBreakerClientWithTimeout.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/retry/clientserver/RetryClientWithDelay.java
While testing the latest RC, I saw a failure I hadn't seen before in `RetryTest` where the timing is fairly tight and the test wasn't using `TCKConfig`.
After fixing that, I had a look through to see if there were any more tests which should clearly be using `TCKConfig` but aren't and I found `CircuitBreakerTimeoutTest` so I've fixed that too.
Fixes #544
=> Add timeout config to RetryTest and CircuitBreakerTimeoutTest

spec/src/main/asciidoc/circuitbreaker.asciidoc, spec/src/main/asciidoc/metrics.asciidoc, tck/pom.xml, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/AllMetricsTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/BulkheadMetricTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/CircuitBreakerMetricBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/CircuitBreakerMetricTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/ClashingNameTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/ClassLevelMetricTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/FallbackMetricBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/FallbackMetricHandler.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/FallbackMetricTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/MetricsDisabledTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/RetryMetricBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/RetryMetricTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/TimeoutMetricTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/util/CounterMetric.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/util/GaugeMetric.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/util/MetricDefinition.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/util/MetricGetter.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/util/RegistryTypeLiteral.java, tck/src/test/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/util/MetricGetterTest.java
Includes spec and TCKs.
We can still make tweaks to the spec if required.
Fixes #401 
Fixes #499
=> Update the spec with the new metrics for 3.0

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/RetryConfigBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/RetryConfigTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/TestConfigExceptionB1.java
Add TCKs to test that each of the attributes of `@Retry` can be configured.
For #407
=> Test configuration of @Retry

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/AllMetricsTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/util/MetricDefinition.java
=> Test metrics are registered with correct units

spec/src/main/asciidoc/asynchronous.asciidoc, spec/src/main/asciidoc/microprofile-fault-tolerance-spec.asciidoc, spec/src/main/asciidoc/optional-container-integration.asciidoc
This is because MicroProfile itself doesn't know anything about
naming or security context, and MicroProfile implementations
don't have to have anything like that. These terms only make sense
in a Java EE environment. Therefore, the requirement that naming
and security contexts are propagated should be present in an extra
section that only applies to Java EE container implementations.
=> move the note about naming/security context propagation to an extra section

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/FallbackConfigTest.java
Noticed this when I was testing my changes to the bulkhead tests.
One of the config lines sets the parameter on the wrong method.
I also added comments consistent with the other config tests.
=> Fix FallbackConfigTest

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/TimeoutConfigBean.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/TimeoutConfigTest.java
=> add TCK tests for configuring @Timeout attributes

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/AllMetricsTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/util/CounterMetric.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/util/GaugeMetric.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/util/MetricGetter.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/util/MetricRegistryProvider.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/util/MetricRegistryProxy.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/util/MetricRegistryProxyHandler.java
This PR uses reflection to work around the differences in API so that the TCK can run with either MP Metrics 2.3 or 3.0.
Most of the reflective nastiness is encapsulated in `MetricRegistryProxy` and `MetricRegistryProxyHandler` leaving the test code fairly clean.
Fixes #570
=> Support running against both MP Metrics 2.3 and 3.0

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/BulkheadMetricTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/TimeoutMetricTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/metrics/util/GaugeMetric.java
Tolerate the following breaking changes in MP Metrics 5.0, while retaining support for MP Metrics 4.0:
- Methods removed from `Snapshot`
- `Gauge<T>` changed to `Gauge<T extends Number>`
- Breaks binary compatibility because method signatures are different after type erasure
This does not include support for tolerating the removal of `@RegistryType`. See #117
Fixes #609
=> Tolerate MP Metrics 5.0 API changes, except MetricsRegistry injection

api/bnd.bnd
This OSGi range as it is is for Jakarta EE 8.
This changes the version range to be usable with Jakarta EE 9.1 (3.x) and 10 (4.x)
Signed-off-by: Andrew Pielage <pandrex247@hotmail.com>
=> Increase jakarta.enterprise.util OSGi Version Range to Encompass Jakarta EE 9.1 and 10

.github/workflows/build.yml
The newest version of maven does not work with Java 8. The jenkins build uses an older version of maven, but github actions have no intention of allowing the confiugration of the maven version actions/setup-java#457
=> Remove broken Java 8 GH action build

spec/src/main/asciidoc/release_notes.asciidoc, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableAnnotationClient.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableAnnotationGloballyEnableOnClassDisableOnMethod.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableAnnotationGloballyEnableOnClassTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableAnnotationGloballyEnableOnMethodTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableAnnotationGloballyTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableAnnotationOnClassEnableOnMethodTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableAnnotationOnClassTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableAnnotationOnMethodsTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableFTEnableGloballyTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableFTEnableOnClassTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/disableEnv/DisableFTEnableOnMethodTest.java
Previously these tests were using a fixed thread pool executor which will create unmanaged threads on a Jakarta EE server.
We already have `AsyncCaller` which is designed to avoid this, and `AsyncTaskManager` which provides additional framework for exactly these type of tests so we should use them here.
Unfortunately these test classes are also testing the disablement of the `@Asynchronous` annotation which `AsyncCaller` and `AsyncTaskManager` use. We could split these tests up, but it's easier to add additional config to enable the annotation for that class specifically.
Fixes #634
=> Make config disabled tests use `AsyncTaskManager`

tck/pom.xml
Specify the dependency on MP Telemetry instead of directly on OTel APIs
=> Final tidyup

api/pom.xml, tck/pom.xml
Mainly trying to fix the messy stylization of 'microProfile-fault-tolerance-api' on public apidocs pages:
https://download.eclipse.org/microprofile/microprofile-fault-tolerance-4.1-RC2/apidocs/
Also, building the project now, the module names are all nice and clean:
````
[INFO] Reactor Summary for MicroProfile Fault Tolerance 4.1-SNAPSHOT:
[INFO]
[INFO] MicroProfile Fault Tolerance ....................... SUCCESS [  4.982 s]
[INFO] MicroProfile Fault Tolerance API ................... SUCCESS [  4.178 s]
[INFO] MicroProfile Fault Tolerance TCK ................... SUCCESS [  7.763 s]
[INFO] MicroProfile Fault Tolerance Specification ......... SUCCESS [  7.148 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
````
=> Minor Maven pom fixes that propagate to the public apidocs pages

tck/pom.xml
In preparation for the 4.1 final release.
Builds expected to fail because Telemetry 2.0 is in the staging repo.
=> Use final version of Telemetry dependency

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/telemetryMetrics/util/InMemoryMetricReader.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/telemetryMetrics/util/PullExporterAutoConfigurationCustomizerProvider.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/telemetryMetrics/util/TelemetryLongMetric.java
While testing the metric test changes, I ran into an issue where the `InMemoryMetricReader` would not be registered correctly for the first test app. This turned out to be because Liberty was initializing OpenTelemetry before CDI was fully initialized.
This could be true for other runtimes as well, so I think we need to make the `InMemoryMetricReader` not depend on CDI.
I changed it to use a static singleton instance, which works in liberty, but I wasn't sure whether that would work for implementations using an embedded arquillian container. For this reason, I've also cleared the static instance when the reader is shut down, with the intention that each new app will get a new instance.
=> Make InMemoryMetricReader not a bean

tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/telemetryMetrics/BulkheadTelemetryTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/telemetryMetrics/CircuitBreakerTelemetryTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/telemetryMetrics/FallbackTelemetryTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/telemetryMetrics/RetryTelemetryTest.java, tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/telemetryMetrics/TimeoutTelemetryTest.java
Test groups are global, not just for single test. This means that multiple test classes may be "in progress" at the same time, which leads to issues in at least one implementation which has global state.
Instead of test groups and `dependsOnGroups`, this commit uses simple `dependsOnMethods`, which is local to the test class.
=> Avoid using test groups for test ordering
